on:
  - push

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        racket-variant: ['CS']
        racket-version: ['8.0']
    name: Test on Racket ${{ matrix.racket-variant }} ${{ matrix.racket-version }} on ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Install llvm
      run: sudo apt-get install llvm clang
    - name: Install Racket
      uses: Bogdanp/setup-racket@v1.1
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: ${{ matrix.racket-variant }}
        version: ${{ matrix.racket-version }}
    - name: Version info
      run: |
        llc --version
        gcc --version
    - name: Run tests
      run: raco test ./iniquity
